// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmbrPqN2YQTUjmDJ2lFOfrg2Scn8xcxk',
    appId: '1:715796617121:web:82edccbd46f6bded985de0',
    messagingSenderId: '715796617121',
    projectId: 'edunote-17e54',
    authDomain: 'edunote-17e54.firebaseapp.com',
    storageBucket: 'edunote-17e54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFwrvqz0tj9SQ6wWzpTIqCecmXn1HxwRc',
    appId: '1:715796617121:android:cbce93f72e82d71b985de0',
    messagingSenderId: '715796617121',
    projectId: 'edunote-17e54',
    storageBucket: 'edunote-17e54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB84nZ-J8NBQ0AU6rQZqg8cOMq9CEMwxIU',
    appId: '1:715796617121:ios:cd82defdf2568671985de0',
    messagingSenderId: '715796617121',
    projectId: 'edunote-17e54',
    storageBucket: 'edunote-17e54.firebasestorage.app',
    iosBundleId: 'com.example.edunote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB84nZ-J8NBQ0AU6rQZqg8cOMq9CEMwxIU',
    appId: '1:715796617121:ios:cd82defdf2568671985de0',
    messagingSenderId: '715796617121',
    projectId: 'edunote-17e54',
    storageBucket: 'edunote-17e54.firebasestorage.app',
    iosBundleId: 'com.example.edunote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABmbrPqN2YQTUjmDJ2lFOfrg2Scn8xcxk',
    appId: '1:715796617121:web:53256b3c3e2eb1f9985de0',
    messagingSenderId: '715796617121',
    projectId: 'edunote-17e54',
    authDomain: 'edunote-17e54.firebaseapp.com',
    storageBucket: 'edunote-17e54.firebasestorage.app',
  );
}
